name = "duty-scheduler"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[pages]
build_output_dir = ".next"

[[pages.functions]]
kv_namespaces = [
  {
    binding = "ONDUTY_KV",
    id = "",
    preview_id = ""
  }
]
